<!--
  Copyright 2017 Lambert Boskamp
  
  Licensed under the Apache License, Version 2.0 (the "License"); you may not
  use this file except in compliance with the License.  You may obtain a copy
  of the License at
  
    http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
  License for the specific language governing permissions and limitations under
  the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.foxysoft.idm</groupId>
  <version>2.0.2-SNAPSHOT</version>
  <packaging>pom</packaging>
  <artifactId>rhidmo</artifactId>
  <modules>
    <module>servlet-jar</module>
    <module>servlet-war</module>
    <module>ear</module>
  </modules>
  <properties>
    <!-- Build timestamp must be static for reproducible builds. -->
    <!-- See https://maven.apache.org/guides/mini/guide-reproducible-builds.html -->
    <project.build.outputTimestamp>2025-12-01T12:43:59Z</project.build.outputTimestamp>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <rhidmo.spotless.version>3.1.0</rhidmo.spotless.version>
    <rhidmo.spotless.javaformat.version>1.28.0</rhidmo.spotless.javaformat.version>
  </properties>
  <build>
    <pluginManagement>
      <plugins>
        <!-- BEGIN: build plugins of module servlet-jar -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.5.1</version>
          <configuration>
            <source>1.8</source>
            <target>1.8</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>0.8.13</version>
          <executions>
            <execution>
              <id>coverage-prepare-agent</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>coverage-report</id>
              <goals>
                <goal>report</goal>
              </goals>
            </execution>
            <execution>
              <id>coverage-check</id>
              <goals>
                <goal>check</goal>
              </goals>
              <configuration>
                <rules>
                  <rule>
                    <element>BUNDLE</element>
                    <limits>
                      <limit>
                        <counter>INSTRUCTION</counter>
                        <value>COVEREDRATIO</value>
                        <!-- Even classes with zero coverage won't fail the build for now -->
                        <minimum>0</minimum>
                      </limit>
                    </limits>
                  </rule>
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${rhidmo.spotless.version}</version>
          <configuration>
            <java>
              <googleJavaFormat>
                <version>${rhidmo.spotless.javaformat.version}</version>
              </googleJavaFormat>
              <removeUnusedImports/>
            </java>
          </configuration>
          <executions>
            <execution>
              <id>format-check</id>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <!-- END: build plugins of module servlet-jar -->
        <!-- BEGIN: build plugins of module ear -->
        <plugin>
          <artifactId>maven-ear-plugin</artifactId>
          <version>3.4.0</version>
          <configuration>
            <version>1.4</version>
            <modules>
              <webModule>
                <groupId>de.foxysoft.idm</groupId>
                <artifactId>rhidmo-servlet-war</artifactId>
                <contextRoot>/rhidmo</contextRoot>
              </webModule>
            </modules>
            <filtering>true</filtering>
            <archive>
              <manifest>
                <addClasspath>true</addClasspath>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>3.7.1</version>
          <configuration>
            <descriptors>
              <descriptor>src/assembly/zip.xml</descriptor>
            </descriptors>
            <appendAssemblyId>false</appendAssemblyId>
          </configuration>
          <executions>
            <execution>
              <id>make-assembly</id>
              <phase>package</phase>
              <goals>
                <goal>single</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>3.6.1</version>
          <executions>
            <execution>
              <!-- Calculating the SDA version number as used in SAP_MANIFEST.MF requires two stages: -->
              <!-- Stage 1: decide whether this is a release or snapshot (development) version -->
              <!-- Stage 2: parse temporary properties from stage 1 to compute final SDA version -->
              <id>transform-build-timestamp-stage-1</id>
              <goals>
                <goal>regex-properties</goal>
              </goals>
              <configuration>
                <regexPropertySettings>
                  <regexPropertySetting>
                    <!-- Input value: Maven project version + "." + build output timestamp -->
                    <value>${project.version}.${project.build.outputTimestamp}</value>
                    <!-- Match RELEASE versions -->
                    <regex>^(\d+\.\d+\.\d+)\.(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z$</regex>
                    <!-- Output property name -->
                    <name>rhidmo.ear.version.rel</name>
                    <!-- If match, output property value will be: -->
                    <!-- "MATCHED:[" + <SEMVER> + "." + <TIMESTAMP_14_DIGITS> + "]"-->
                    <replacement>MATCHED:[$1.$2$3$4$5$6$7]</replacement>
                    <!-- If no match, output property value will be as given in VALUE element (not empty!)-->
                    <failIfNoMatch>false</failIfNoMatch>
                  </regexPropertySetting>
                  <regexPropertySetting>
                    <!-- Input value: Maven project version + "." + build output timestamp -->
                    <value>${project.version}.${project.build.outputTimestamp}</value>
                    <!-- Match SNAPSHOT (development) versions -->
                    <regex>^(\d+\.\d+\.\d+)-SNAPSHOT.+$</regex>
                    <!-- Output property name -->
                    <name>rhidmo.ear.version.dev</name>
                    <!-- If match, output property value will be: -->
                    <!-- "MATCHED:[" + <SEMVER> + "." + <DUMMY_14_ZEROES> + "]"-->
                    <replacement>MATCHED:[$1.00000000000000]</replacement>
                    <!-- If no match, output property value will be as given in VALUE element (not empty!)-->
                    <failIfNoMatch>false</failIfNoMatch>
                  </regexPropertySetting>
                </regexPropertySettings>
              </configuration>
            </execution>
            <execution>
              <!-- Now for stage 2: parse the concatenation of ${rhidmo.ear.version.rel}${rhidmo.ear.version.dev} -->
              <!-- and pick the one that actually MATCHED in stage 1; discard the other -->
              <id>transform-build-timestamp-stage-2</id>
              <goals>
                <goal>regex-properties</goal>
              </goals>
              <configuration>
                <!-- Calculate SDA version number as used in SAP_MANIFEST.MF -->
                <regexPropertySettings>
                  <regexPropertySetting>
                    <!-- Input value -->
                    <value>${rhidmo.ear.version.rel}:${rhidmo.ear.version.dev}</value>
                    <!-- Note we must use an ANCHORED regex from start ^ to end $ -->
                    <!-- otherwise any characters before or after our regex match -->
                    <!-- will be implicitly included in the replacement. -->
                    <regex>^.*MATCHED:\[([^\]]+)\].*$</regex>
                    <!-- Output property name -->
                    <name>rhidmo.ear.version</name>
                    <!-- Final output property value: -->
                    <!-- For release versions: <SEMVER> + "." + <TIMESTAMP_14_DIGITS> -->
                    <!-- For snapshot versions: <SEMVER> + "." + <DUMMY_14_ZEROES> -->
                    <replacement>$1</replacement>
                    <!-- Failure here in stage 2 would indicate a programming error -->
                    <failIfNoMatch>true</failIfNoMatch>
                  </regexPropertySetting>
                </regexPropertySettings>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <!-- END: build plugins of module ear -->
      </plugins>
    </pluginManagement>
  </build>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>de.foxysoft.idm</groupId>
        <artifactId>rhidmo-servlet-war</artifactId>
        <version>${project.version}</version>
        <type>war</type>
      </dependency>
      <dependency>
        <groupId>de.foxysoft.idm</groupId>
        <artifactId>rhidmo-servlet-jar</artifactId>
        <version>${project.version}</version>
        <type>war</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <profiles>
    <profile>
      <id>java-8-spotless-disabled</id>
      <activation>
        <!-- Activate this profile automatically as fallback on older JDK versions starting with Java 8 -->
        <!-- since spotless version used for production wouldn't even load on these old JDKs. -->
        <!-- The purpose is to have a build that can seamlessly COMPILE + FORMAT on Java 17+, -->
        <!-- but which is still able to COMPILE (without formatting) on Java 8. -->
        <jdk>[1.8,17)</jdk>
      </activation>
      <properties>
        <!-- Trial and error has shown that this version of spotless build plugin is compatible with Java 8. -->
        <!-- Declaring this version on Java 8 ensures that the build plugin can be successfully LOADED. -->
        <rhidmo.spotless.version>2.29.0</rhidmo.spotless.version>
        <rhidmo.spotless.javaformat.version>1.7</rhidmo.spotless.javaformat.version>
        <!-- However, never actually RUN spotless in this profile, because the old google-java-format 1.7 -->
        <!-- supported by that spotless version produces entirely different results from what we want. -->
        <spotless.skip>true</spotless.skip>
      </properties>
    </profile>
  </profiles>
</project>
